# -------------------------------------------------------------------------------------------------------------
# File: training.py
# Project: DAA*: Deep Angular A Star for Image-based Path Planning
# Contributors:
#     Zhiwei Xu <zwxu064@gmail.com>
#
# Copyright (c) 2025 Zhiwei Xu
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
# documentation files (the "Software"), to deal in the Software without restriction, including without
# limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or substantial
# portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
# LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
# -------------------------------------------------------------------------------------------------------------

import random
import re
import sys
import os
import numpy as np
import torch
import torch.optim
import torch.nn as nn


sys.path.append(f"{os.path.dirname(os.path.abspath(__file__))}/../..")

from src.models.actor.daastar.astar import VanillaAstar, NeuralAstar

from typing import Optional

from transformers.modeling_outputs import SemanticSegmenterOutput

from src.utils.daastar_util import parse_args


# =============================================================================================================

def compare_two_vectors(
    v_src,
    v_tar
):
    assert v_src.shape[0] == v_tar.shape[0]
    equal = (v_tar == v_src).float().sum()
    gre = (v_tar > v_src).float().sum()
    less = (v_tar < v_src).float().sum()

    return {'less': less.cpu(), 'equal': equal.cpu(), 'gre': gre.cpu()}

# =============================================================================================================

def load_from_ptl_checkpoint(checkpoint_path):
    print(f"Resume from {checkpoint_path}")
    state_dict = torch.load(checkpoint_path)["state_dict"]
    state_dict_extracted = dict()

    for key in state_dict:
        if "planner" in key:
            state_dict_extracted[re.split("planner.", key)[-1]] = state_dict[key]

    return state_dict_extracted

# =============================================================================================================

class DAAStarPlannerModule(nn.Module):
    def __init__(
        self,
        config,
    ):
        super().__init__()
        # While aug_tmpd also support vanilla a star, it is too slow, so igore it here
        vastar_available_list = ['street', 'tmpd', 'mpd']

        # use config from the paper
        config = parse_args("baselines/daastar/model/full_config.yaml")

        planner = NeuralAstar(config)

        self.planner = planner
        self.vanilla_astar = VanillaAstar(config)
        self.config = config
        self.global_direction_weight = []
        self.EPS = 1e-10
        self.support_vastar = config.dataset_name in vastar_available_list
        self.loss_fnc = nn.L1Loss()

        # To store ground truth paths generated by python_motion_planning.
        # Basically for mpd, tmpd, street because empirical dijkstra policy
        # from NeuralA* repo has zig-zag.
        # This will store with epoch, so would be a bit slow.
        self.train_set = {'inputs': [], 'solutions': []}
        self.val_set = {'inputs': [], 'solutions': []}

        # Save time by avoiding runing vanilla a star
        if config.dataset_name in ['aug_tmpd']:
            self.path_loss_weight = config.transpath.path_loss_weight
            self.enable_mask = config.transpath.mask
        else:
            self.path_loss_weight = 1.0
            self.enable_mask = False

        # Not run vanilla A* on aug_tmpd, too slow.
        if self.support_vastar is False and config.dataset_name != "aug_tmpd":
            print(f'!!! {config.dataset_name} does not support vanilla A*.')

        if config.dataset_name in ['aug_tmpd'] and not config.enable_motion_planning_lib:
            self.recon_criterion = nn.L1Loss() if config.transpath.mode == 'h' else nn.MSELoss()
        else:
            self.recon_criterion = None

        self.automatic_optimization = False

    def infer(
        self,
        map_designs,
        start_maps,
        goal_maps,
        store_hist_coordinates=False,
        prob_maps=None,
        disable_compute_path_angle=False
    ):
        return self.planner(
            map_designs,
            start_maps,
            goal_maps,
            store_hist_coordinates=store_hist_coordinates,
            prob_maps=prob_maps,
            disable_compute_path_angle=disable_compute_path_angle
        )

    def configure_optimizers(self):
        lr = self.config.params.lr

        return torch.optim.RMSprop(self.planner.parameters(), lr)

    def forward(
        self,
        images: torch.FloatTensor,
        labels: Optional[torch.LongTensor] = None,
        starts: Optional[torch.LongTensor] = None,
        ends: Optional[torch.LongTensor] = None,
        loss_fn: nn.Module = None,  # computes loss only if not set to None, uses IL loss all of the time
    ):
        
        obstacle_color = torch.tensor([76 / 255, 76 / 255, 255 / 255], device=images.device)  # BLUE
        obstacle_map = torch.sigmoid((images - obstacle_color.view(3, 1, 1)).abs()).sum(1, keepdim=True)
        walkable_map = (~(obstacle_map < 1.51)).float()  # obstacles will have a value of 3 * sig(0.0) = 1.5, add small margin to be safe against numerical inaccuracies

        start_color = torch.tensor([255 / 255, 76 / 255, 76 / 255], device=images.device)  # BLUE
        start_map = torch.sigmoid((images - start_color.view(3, 1, 1)).abs()).sum(1, keepdim=True)
        start_map = (start_map < 1.51).float()  # obstacles will have a value of 3 * sig(0.0) = 1.5, add small margin to be safe against numerical inaccuracies

        end_color = torch.tensor([76 / 255, 255 / 255, 76 / 255], device=images.device)  # BLUE
        end_map = torch.sigmoid((images - end_color.view(3, 1, 1)).abs()).sum(1, keepdim=True)
        end_map = (end_map < 1.51).float()  # obstacles will have a value of 3 * sig(0.0) = 1.5, add small margin to be safe against numerical inaccuracies

        # print("Walkable at start/goal: ", walkable_map[start_map < 1.51], walkable_map[end_map < 1.51])

        map_designs = walkable_map
        start_maps = start_map
        goal_maps = end_map
        opt_trajs = labels.unsqueeze(1).float()

        # Ignore invalid opt_trajs samples
        valid_sample_indices = opt_trajs.sum((1, 2, 3)) > 2
        map_designs = map_designs[valid_sample_indices]
        start_maps = start_maps[valid_sample_indices]
        goal_maps = goal_maps[valid_sample_indices]
        opt_trajs = opt_trajs[valid_sample_indices]
        num_samples = map_designs.shape[0]

        prob_maps = None

        outputs, cost_maps = self.infer(
            map_designs,
            start_maps,
            goal_maps,
            prob_maps=prob_maps,
        )  # THIS IS NOT THE COST MAP!!!!!!!!!!!!! Its the pred map = 1 - cost map

        cost_map_loss = 0
        loss = 0

        if self.config.dataset_name in ['aug_tmpd']:
            # NOTE: use arithmetic inversion to keep values in [0, 1]; bitwise NOT yields negatives.
            gt_cost_maps = labels.float().unsqueeze(1)
            print(f"Gt cost maps: [{gt_cost_maps.min()}, {gt_cost_maps.max()}], mean: {gt_cost_maps.mean()}")
            print(f"Pred cost maps: [{cost_maps.min()}, {cost_maps.max()}], mean: {cost_maps.mean()}")

            if self.enable_mask:
                # print("Mask enabled!!!!!")
                # It is actually PPM, and this is to exclude high prob areas
                # such that they can be learned through path loss
                cost_map_mask = cost_maps < 0.5  # only consider the less prob areas
                cost_map_loss = self.recon_criterion(
                    cost_maps[cost_map_mask],
                    gt_cost_maps[cost_map_mask]
                )
            else:
                cost_map_loss = self.recon_criterion(cost_maps, gt_cost_maps)
                # MOD: Lets see if this stops it from collapsing
                # scaled_cost_map_loss = F.mse_loss(cost_maps, gt_cost_maps, reduction="none") * ((gt_cost_maps * 10) + 1)
                # cost_map_loss = scaled_cost_map_loss.mean()

        path_histories = outputs.histories

        if self.config.dataset_name in ['aug_tmpd']:
            if self.config.transpath.loss_mode.find('path') > -1:
                # print("Path")
                # print(f"Path history maps: [{path_histories.min()}, {path_histories.max()}], mean: {path_histories.mean()}")
                # print(f"Opt traj maps: [{opt_trajs.min()}, {opt_trajs.max()}], mean: {opt_trajs.mean()}")
                # print("Path loss weight: ", self.path_loss_weight)
                path_loss = self.loss_fnc(path_histories, opt_trajs)
                path_loss = self.path_loss_weight * path_loss
                loss += path_loss
                print("Path loss", path_loss)
            if self.config.transpath.loss_mode.find('heat') > -1:
                # print("Heat")
                loss += cost_map_loss
                print("Cost map loss", cost_map_loss)
        else:
            print("else")
            path_loss = self.loss_fnc(path_histories, opt_trajs)
            loss += path_loss
            print("Path loss", path_loss)
    
        return SemanticSegmenterOutput(
            loss=loss,
            logits=outputs.paths.squeeze(1),
            hidden_states=outputs.histories.squeeze(1),
            attentions=None,
        )

# =============================================================================================================

def set_global_seeds(seed):
    torch.manual_seed(seed)

    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
        torch.backends.cudnn.deterministic = True
        torch.backends.cudnn.benchmark = False

    np.random.seed(seed)
    random.seed(seed)